version: '3'
services:
  backend:
    build:
      context: ./be          # 기존 ./backend에서 ./be로 수정
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "8080:8080"
    networks:
      - mynet

  frontend:
    build:
      context: ./fe          # 기존 ./frontend에서 ./fe로 수정
      dockerfile: Dockerfile
    container_name: frontend
    # frontend 컨테이너 자체가 80 포트를 열고 있음
    ports:
      - "80:80"z
    networks:
      - mynet

networks:
  mynet:
    driver: bridge 
